### ISSUE TITLE
error jsonxx.h:400

### ISSUE THREAD

**Issue by icelove88** [dynexcoin/Dynex#10]
[JSONXX] expression 'has<T>(key)' failed at C:\DYNEX\DynexSolve\DynexSolveVS\DynexSolveVS\jsonxx.h:400 -> Assertion failed: 0, file C:\DYNEX\DynexSolve\DynexSolveVS\DynexSolveVS\jsonxx.cc, line 30

**Comment by QQ40451** [comment]
the same error

**Comment by dynexcoin** [comment]
Resolved in version 2.1.1
