### ISSUE TITLE
strat_mining unkone command

### ISSUE THREAD

**Issue by jiuyaopinyin** [dynexcoin/Dynex#12]
in simplewallet
![WX20221204-020814@2x](https://user-images.githubusercontent.com/16219599/205455584-e5a952d6-a0fe-4f17-a136-ce6913aa2c62.png)

**Comment by jiuyaopinyin** [comment]
![WX20221204-032033@2x](https://user-images.githubusercontent.com/16219599/205458130-f8896f46-0650-49ce-a226-12d975049af1.png)

**Comment by dynexcoin** [comment]
Mining from the wallet is not supported since the algo change to DynexSolve. You need to run DynexSolve to mine.
