### ISSUE TITLE
ailed to send message: {"jsonrpc":"2.0","id":1,"method":"submit","params":

### ISSUE THREAD

**Issue by JohnTeddy3** [dynexcoin/Dynex#14]
04-12-2022 10:21:22 [STRATUM] SUBMITTING PoW: 86ff38dea15ccb94e02eabeafa23e1cac8dd342d8defca62a65af99e5d1a0100 (difficulty = 1000)
04-12-2022 10:21:22 [STRATUM] failed to send message: {"jsonrpc":"2.0","id":1,"method":"submit","params":{"id":"193548390789176","job_id":"290687014747009","nonce":"6637e4af","result":"86ff38dea15ccb94e02eabeafa23e1cac8dd342d8defca62a65af99e5d1a0100","algo":"dynexsolve"}}

**Comment by dynexcoin** [comment]
Resolved in version 2.1.1. miner will now automatically re-login with the pool

**Comment by JohnTeddy3** [comment]
么，收到此条消息，证明我的代理已经帮我收到来信啦。
