### ISSUE TITLE
 expression 'has<T>(key)' 

### ISSUE THREAD

**Issue by QQ40451** [dynexcoin/Dynex#16]
04-12-2022 22:24:50 [MALLOB] MESSAGE: SSL connect error
[JSONXX] expression 'has<T>(key)' failed at C:\DYNEX\DynexSolve\DynexSolveVS\DynexSolveVS\jsonxx.h:400 -> Assertion failed: 0, file C:\DYNEX\DynexSolve\DynexSolveVS\DynexSolveVS\jsonxx.cc, line 30

**Comment by dynexcoin** [comment]
Resolved in version 2.1.1
