### ISSUE TITLE
[JSONXX] expression 'has<T>(key)' failed at C:\DYNEX\DynexSolve\DynexSolveVS\Dyn exSolveVS\jsonxx.h:400

### ISSUE THREAD

**Issue by Denw800** [dynexcoin/Dynex#17]
C:\Users\User\Desktop\dynexsolve_windows2.1.0\dynexsolve_windows2.1.0>dynexsolve
vs.exe -mining-address ***************************************************.3rtx3080 -daemon-host dynexnode.fairhas
h.org -no-cpu -multi-gpu -stratum-url pool.dnx.fairhash.org -stratum-port 2335 -
stratum-password x -mallob-endpoint https://dynex.dyndns.org/dynexmallob/
04-12-2022 22:31:11 [INFO] -----------------------------------------------------
----
04-12-2022 22:31:11 [INFO] DynexSolve v2.1.0 | Meaningful Mining
04-12-2022 22:31:11 [INFO] -----------------------------------------------------
----
04-12-2022 22:31:11 [INFO] STRATUM PROTOCOL ENABLED
04-12-2022 22:31:11 [INFO] STRATUM URL SET TO pool.dnx.fairhash.org
04-12-2022 22:31:11 [INFO] STRATUM PORT SET TO 2335
04-12-2022 22:31:11 [INFO] STRATUM PASSWORD SET TO x
04-12-2022 22:31:11 [INFO] MINING ADDRESS SET TO ***************************************.3rtx3080
04-12-2022 22:31:11 [INFO] OPTION daemon-host SET TO dynexnode.fairhash.org
04-12-2022 22:31:11 [INFO] OPTION mallob-endpoint SET TO https://dynex.dyndns.or
g/dynexmallob/
04-12-2022 22:31:11 [INFO] OPTION multi-gpu ACTIVATED
04-12-2022 22:31:11 [INFO] OPTION -no-cpu ACTIVATED
04-12-2022 22:31:11 [INFO] FOUND 3 INSTALLED GPU(s)
04-12-2022 22:31:11 [INFO] MULTI-GPU ENABLED: FOUND 3 GPUs
04-12-2022 22:31:11 [INFO] CONNECTING TO DYNEX MALLOB ENDPOINT https://dynex.dyn
dns.org/dynexmallob/... OK
04-12-2022 22:31:17 [MALLOB] INFO: NETWORK FLOPS = -4262939601 kFLOPS | HR = -21
46672660 H
04-12-2022 22:31:17 [MALLOB] UNIQUE MALLOB NETWORK_ID: 46c633532da22c01964bbee07
47d06ac66e74aa381dcdbdb4f4b40d817f1905e (64)
04-12-2022 22:31:19 [MALLOB] REGISTERED AS NEW WORKER: SUCCESS.
04-12-2022 22:31:21 [MALLOB] JOB RECEIVED
04-12-2022 22:31:21 [MALLOB] JOB_ID              : 6
04-12-2022 22:31:21 [MALLOB] CHIPS AVAILABLE     : 70393/3521856
04-12-2022 22:31:21 [MALLOB] JOB FILENAME        : dynex_compute_w340.cnf
04-12-2022 22:31:21 [MALLOB] JOB FEE             : BLOCK REWARD + 0 DNX
04-12-2022 22:31:21 [MALLOB] JOB SOLUTION REWARD : 100000 DNX
04-12-2022 22:31:21 [INFO] LOADING FILE dynex_compute_w340.cnf
04-12-2022 22:31:21 [INFO] VARIABLES : 220116
04-12-2022 22:31:21 [INFO] CLAUSES   : 839376
04-12-2022 22:31:21 [INFO] RATIO     : 3.813335
04-12-2022 22:31:22 [INFO] LOADING   : 100.00%
04-12-2022 22:31:22 [INFO] 183136928 BYTES ALLOCATED...
04-12-2022 22:31:23 [INFO] BUILDING CIRCUIT(1/2): 839376/839376
04-12-2022 22:31:24 [INFO] BUILDING CIRCUIT(2/2): 440232/440232
04-12-2022 22:31:24 [INFO] FORMULATION LOADED.
04-12-2022 22-31-24 [CPU] STARTING 0 DYNEX CHIPS ON CPU
04-12-2022 22:31:24 [BLOCKCHAIN] STARTING DYNEXSOLVE SERVICE
04-12-2022 22:31:24 [STRATUM] CONNECTING TO pool.dnx.fairhash.org:2335
04-12-2022 22:31:24 [STRATUM] CONNECTED, LOGGING IN...
04-12-2022 22:31:24 [STRATUM] CONNECTED WITH ID 2543901323881445
04-12-2022 22:31:25 [INFO] UPPER BOUND COMPLEXITY: 3521856 PARALLEL DYNEX CHIPS,
 MAX O(n^5)=9223372036854775808 STEPS
04-12-2022 22:31:25 [GPU 0] SET cudaDeviceSetLimit: 10305257472 BYTES
04-12-2022 22:31:25 [GPU 0] GET cudaDeviceGetLimit: 10305273856 BYTES
04-12-2022 22:31:25 [GPU 1] SET cudaDeviceSetLimit: 10322599936 BYTES
04-12-2022 22:31:25 [GPU 1] GET cudaDeviceGetLimit: 10322640896 BYTES
04-12-2022 22:31:26 [GPU 2] SET cudaDeviceSetLimit: 10322599936 BYTES
04-12-2022 22:31:26 [GPU 2] GET cudaDeviceGetLimit: 10322640896 BYTES
04-12-2022 22:31:26 [GPU 0] CORE DATA COPIED TO GPU 0
04-12-2022 22:31:26 [GPU 1] CORE DATA COPIED TO GPU 1
04-12-2022 22:31:26 [GPU 2] CORE DATA COPIED TO GPU 2
04-12-2022 22:31:26 [INFO] BASE MEMORY REQUIRED: 195850856 BYTES
04-12-2022 22:31:26 [INFO] MEMORY REQUIRED PER DYNEX CHIP: 5943207 BYTES
04-12-2022 22:31:26 [INFO] MAX DYNEX CHIPS FITTING IN MEMORY (ALL GPUs): 5107
04-12-2022 22:31:26 [INFO] PARALLEL DYNEX CHIPS REQUIRED: 3521856
04-12-2022 22:31:26 [INFO] ==> PREPARING 5107 DYNEX CHIPS...
04-12-2022 22:31:26 [GPU 0] PREPARING 1701 DYNEX CHIPS...
04-12-2022 22:31:26 [GPU 0] ALLOCATING MEMORY...  DONE.
04-12-2022 22:31:45 [GPU 0] ALLOCATED 6739523595 BYTES.
04-12-2022 22:31:45 [GPU 0] INITIALIZING CHIPS... DONE
04-12-2022 22:31:45 [GPU 0] COPYING PROBLEM... DONE
04-12-2022 22:31:45 [GPU 0] COPYING CHIP TABLES... DONE
04-12-2022 22:31:50 [GPU 0] INITITALIZED.
04-12-2022 22:31:50 [GPU 1] PREPARING 1703 DYNEX CHIPS...
04-12-2022 22:31:50 [GPU 1] ALLOCATING MEMORY...  DONE.
04-12-2022 22:32:11 [GPU 1] ALLOCATED 6747447785 BYTES.
04-12-2022 22:32:11 [GPU 1] INITIALIZING CHIPS... DONE
04-12-2022 22:32:12 [GPU 1] COPYING PROBLEM... DONE
04-12-2022 22:32:12 [GPU 1] COPYING CHIP TABLES... DONE
04-12-2022 22:32:15 [GPU 1] INITITALIZED.
04-12-2022 22:32:15 [GPU 2] PREPARING 1703 DYNEX CHIPS...
04-12-2022 22:32:15 [GPU 2] ALLOCATING MEMORY...  DONE.
04-12-2022 22:32:32 [GPU 2] ALLOCATED 6747447785 BYTES.
04-12-2022 22:32:33 [GPU 2] INITIALIZING CHIPS... DONE
04-12-2022 22:32:33 [GPU 2] COPYING PROBLEM... DONE
04-12-2022 22:32:33 [GPU 2] COPYING CHIP TABLES... DONE
04-12-2022 22:32:36 [GPU 2] INITITALIZED.
04-12-2022 22:32:39 [MALLOB] CAPACITY NOTIFICATION SENT
[JSONXX] expression 'has<T>(key)' failed at C:\DYNEX\DynexSolve\DynexSolveVS\Dyn
exSolveVS\jsonxx.h:400 -> Assertion failed: 0, file C:\DYNEX\DynexSolve\DynexSol
veVS\DynexSolveVS\jsonxx.cc, line 30

**Comment by dynexcoin** [comment]
Resolved in version 2.1.1
