### ISSUE TITLE
[MALLOB] REGISTER WORKER FAILED

### ISSUE THREAD

**Issue by vlasinus** [dynexcoin/Dynex#24]
Ubuntu 18.04 (HiveOs)
------------------------------------------------------------
./dynexsolve -mining-address XwmfCXTeFU9Ad1LiQ5nzNeNPoQEcCzQY46BmQUUXs7KGYzJkxDEDKqPXpF1fuiHPjMBccfLGv888C7azvWvqbAFa2UpPa -no-cpu -multi-gpu -stratum-url dynex.neuropool.net -stratum-port 19331 -stratum-password x -stratum-paymentid cfd9a4596ec06bab1ca758e0cfa92fe6c8c94b6ee6f79edfebf3d17e4daf
18-12-2022 11:09:35 [INFO] ---------------------------------------------------------
18-12-2022 11:09:35 [INFO] DynexSolve v2.2.1 | Meaningful Mining 
18-12-2022 11:09:35 [INFO] ---------------------------------------------------------
18-12-2022 11:09:35 [INFO] STRATUM PROTOCOL ENABLED 
18-12-2022 11:09:35 [INFO] STRATUM URL SET TO dynex.neuropool.net
18-12-2022 11:09:35 [INFO] STRATUM PORT SET TO 19331
18-12-2022 11:09:35 [INFO] STRATUM PAYMENT ID SET TO cfd9a4596ec06bab1ca758e0cfa92fe6c8c94b6ee6f79edfebf3d17e4daf
18-12-2022 11:09:35 [INFO] STRATUM PASSWORD SET TO x
18-12-2022 11:09:35 [INFO] MINING ADDRESS SET TO XwmfCXTeFU9Ad1LiQ5nzNeNPoQEcCzQY46BmQUUXs7KGYzJkxDEDKqPXpF1fuiHPjMBccfLGv888C7azvWvqbAFa2UpPa
18-12-2022 11:09:35 [INFO] OPTION multi-gpu ACTIVATED
18-12-2022 11:09:35 [INFO] OPTION -no-cpu ACTIVATED
18-12-2022 11:09:35 [INFO] FOUND 3 INSTALLED GPU(s)
18-12-2022 11:09:35 [INFO] MULTI-GPU ENABLED: FOUND 3 GPUs
18-12-2022 11:09:35 [MALLOB] UNIQUE MALLOB NETWORK_ID: 2f136a93ea4ccf89062aab3d534f39ecfeefe484fdde6a3b3c84057ec8d1d6f7 (64)
18-12-2022 11:09:40 [MALLOB] REGISTER WORKER FAILED: {
	"result": false 
}

**Comment by yurimoe** [comment]
I got the same error
