### ISSUE TITLE
Error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by valuevn** [dynexcoin/Dynex#26]
I got the problem like that on ubuntu 18.04

19-12-2022 16:08:36 [INFO] ---------------------------------------------------------
19-12-2022 16:08:36 [INFO] DynexSolve v2.2.1 | Meaningful Mining
19-12-2022 16:08:36 [INFO] ---------------------------------------------------------
19-12-2022 16:08:36 [INFO] STRATUM PROTOCOL ENABLED
19-12-2022 16:08:36 [INFO] STRATUM URL SET TO dynex.neuropool.net
19-12-2022 16:08:36 [INFO] STRATUM PORT SET TO 19331
19-12-2022 16:08:36 [INFO] STRATUM PASSWORD SET TO MyRig
19-12-2022 16:08:36 [INFO] MINING ADDRESS SET TO X-----------------------------Hide-------------------------------
19-12-2022 16:08:36 [INFO] OPTION multi-gpu ACTIVATED
19-12-2022 16:08:36 [INFO] OPTION -no-cpu ACTIVATED
19-12-2022 16:08:36 [INFO] FOUND 1 INSTALLED GPU(s)
19-12-2022 16:08:36 [INFO] MULTI-GPU ENABLED: FOUND 1 GPUs
19-12-2022 16:08:36 [MALLOB] UNIQUE MALLOB NETWORK_ID: 5eaa9c6e6c5c5630a1633a73237e498cc2bc3a168faeef81198b1a67c6e27424 (64)
19-12-2022 16:08:36 [MALLOB] REGISTER WORKER: SUCCESS
19-12-2022 16:08:37 [MALLOB] JOB RECEIVED
19-12-2022 16:08:37 [MALLOB] JOB_ID              : 10
19-12-2022 16:08:37 [MALLOB] CHIPS AVAILABLE     : 329267/3521856
19-12-2022 16:08:37 [MALLOB] JOB FILENAME        : dynex_compute_w340.cnf
19-12-2022 16:08:37 [MALLOB] JOB FEE             : BLOCK REWARD + 0 DNX
19-12-2022 16:08:37 [MALLOB] JOB SOLUTION REWARD : 100000 DNX
19-12-2022 16:08:37 [MALLOB] dynex_compute_w340.cnf NEEDS TO BE DOWNLOADED...
19-12-2022 16:08:40 [MALLOB] FILE SUCCESSFULLY DOWNLOADED.
19-12-2022 16:08:40 [INFO] LOADING FILE dynex_compute_w340.cnf
19-12-2022 16:08:40 [INFO] VARIABLES : 220116
19-12-2022 16:08:40 [INFO] CLAUSES   : 839376
19-12-2022 16:08:40 [INFO] RATIO     : 3.813335
19-12-2022 16:08:41 [INFO] LOADING   : 100.00%
19-12-2022 16:08:41 [INFO] 183136928 BYTES ALLOCATED...
19-12-2022 16:08:41 [INFO] BUILDING CIRCUIT(1/2): 839376/839376
19-12-2022 16:08:41 [INFO] BUILDING CIRCUIT(2/2): 440232/440232
19-12-2022 16:08:41 [INFO] FORMULATION LOADED.
19-12-2022 16:08:41 [INFO] UPPER BOUND COMPLEXITY: 3521856 PARALLEL DYNEX CHIPS, MAX O(n^5)=0 STEPS
19-12-2022 16:08:41 [GPU 0] SET cudaDeviceSetLimit: 11935678464 BYTES
19-12-2022 16:08:41 [GPU 0] GET cudaDeviceGetLimit: 11935678464 BYTES
19-12-2022 16:08:41 [GPU 0] CORE DATA COPIED TO GPU 0
19-12-2022 16:08:41 [INFO] BASE MEMORY REQUIRED: 195850848 BYTES
19-12-2022 16:08:41 [INFO] MEMORY REQUIRED PER DYNEX CHIP: 5943207 BYTES
19-12-2022 16:08:41 [INFO] MAX DYNEX CHIPS FITTING IN MEMORY (ALL GPUs): 1975
19-12-2022 16:08:41 [INFO] PARALLEL DYNEX CHIPS REQUIRED: 3521856
19-12-2022 16:08:41 [INFO] ==> PREPARING 1975 DYNEX CHIPS...
19-12-2022 16:08:41 [GPU 0] PREPARING 1975 DYNEX CHIPS...
19-12-2022 16:08:41 [GPU 0] ALLOCATING MEMORY...  DONE.
19-12-2022 16:08:43 [GPU 0] ALLOCATED 7825137625 BYTES.
19-12-2022 16:08:43 [GPU 0] INITIALIZING CHIPS...  [INFO] Error: no kernel image is available for execution on the device
19-12-2022 16:08:43 [INFO] EXIT WITH ERROR.

**Comment by dynexcoin** [comment]
Obsolete by now
