### ISSUE TITLE
cannot enter command in command line wallet

### ISSUE THREAD

**Issue by gammabu** [dynexcoin/Dynex#27]
windows
dynex deamon v2.2.2 SYNCHRONIZED OK
DYNEX wallet v2.2.2

password: **********
2022-Dec-20 10:28:06.455904 INFO    Loading wallet...
2022-Dec-20 10:28:06.470406 INFO    Consumer added, consumer 000001D60585C320, count 1
2022-Dec-20 10:28:06.477409 INFO    Loading...
2022-Dec-20 10:28:06.480910 INFO    Loaded
2022-Dec-20 10:28:06 INFO    Loaded 2 known transfer(s)
2022-Dec-20 10:28:06.493912 INFO    Starting...
2022-Dec-20 10:28:06.497411 INFO    Opened wallet: <my wallet address>
2022-Dec-20 10:28:06.506913 INFO    **********************************************************************
Use "help" command to see the list of available commands.
**********************************************************************
2022-Dec-20 10:28:06.506913 INFO    Removing outdated pool transactions...
2022-Dec-20 10:28:06.530918 INFO    Outdated pool transactions processed

![image](https://user-images.githubusercontent.com/121070930/208561040-0d4923e6-7067-4247-af5d-5758b4845f49.png)

**Comment by theONEwalker** [comment]
i was have the same problem...i was solved using the bak file wallet(*.bin.walletbak), and/or deleted *.bin.wallet
