### ISSUE TITLE
Please add support for command line lock-clock, core offset , mem parameters.

### ISSUE THREAD

**Issue by UserDC-LeGrand** [dynexcoin/Dynex#34]
To increase efficiency even more for this new POuW coin, please add support for command line lock-clock, core offset , mem parameters.

Similar to the commandline "nvtool --setcoreoffset 255 --setclocks 2200 --setmem 810".

Thanks for the providing this miner!

Hope to see fully integrated in HiveOS soon, instead of using custom miner option.

**Comment by danilokrasic** [comment]
yeah same here.. really chearing for that

**Comment by dynexcoin** [comment]
Obsolete by now
