### ISSUE TITLE
not enough hasrate report

### ISSUE THREAD

**Issue by trueminer11** [dynexcoin/Dynex#39]
I use ekapool and neuropool to mine dnx, this screenshot show hashrate report 378H/s but on pool is only about 129 H/s, anyone have same problem ?
![3](https://user-images.githubusercontent.com/124549129/216885378-6954a730-58fd-42bf-a3f1-64f2fad78124.png)

**Comment by MarioCoarasa** [comment]
HI, I have same problem with all miners, besides, the payment was according pool report, so, i had to change to other coin. _

**Comment by 13y87t** [comment]
Low end cpu = low hashrate Also with srbminer hashrate has made ~ x3, so difficulty jump up. Dynexsolve is obsolete for now

If you have string cpu, use srbminer 2.2.0 with AMD, or 2.2.1 with NVIDIA

**Comment by dynexcoin** [comment]
Obsolete by now
