### ISSUE TITLE
Illegal instruction

### ISSUE THREAD

**Issue by belgeran** [dynexcoin/Dynex#40]
```
06-02-2023 12:45:15 [GPU 0] 132835829 STEPS (+87803531) | 20.96s | FLOPS = 4189 kFLOPS | HR = 77.182 H | AVG(O)n ^ 0.89026 | CIRCUIT SIMULATION (0.00h)
06-02-2023 12:45:15 [GPU 1] 134072855 STEPS (+87457674) | 20.96s | FLOPS = 4172 kFLOPS | HR = 81.700 H | AVG(O)n ^ 0.88897 | CIRCUIT SIMULATION (0.00h)
06-02-2023 12:45:15 [GPU 2] 135427502 STEPS (+88767938) | 20.96s | FLOPS = 4235 kFLOPS | HR = 83.509 H | AVG(O)n ^ 0.88989 | CIRCUIT SIMULATION (0.00h)
06-02-2023 12:45:15 [GPU *] 402336186 STEPS (+264029143) | 20.96s | FLOPS = 12596 kFLOPS | HR = 242.391 H | AVG(O)n ^ 0.88971
06-02-2023 12:45:15 [INFO] POOL HASHRATE 0 (0/0) UPTIME 9
06-02-2023 12:45:15 [STRATUM] CONNECTING TO dnx.sg.ekapool.com:19666
06-02-2023 12:45:15 [STRATUM] CONNECTED, LOGGING IN... 
06-02-2023 12:45:15 [STRATUM] AUTHORIZED
06-02-2023 12:45:15 [STRATUM] JOB ID 921590304568389 DIFF 15000
./run_dynex.sh: line 6: 26703 Illegal instruction     (core dumped) ./dynexsolve -mining-address <address> -no-cpu -multi-gpu -stratum-url dnx.sg.ekapool.com -stratum-port 19666 -mallob-endpoint https://dnx.sg.ekapool.com/ -stratum-password <password>

```

Ubuntu 20.04.5 LTS
Dual E5-2650v2
Downloaded the 20.04 AVX package, but it didn't work.... tried going generic but doesn't work either

Using generic dynexsolve, with compiled source code gives this error on Ubuntu 20.04
./dynexsolve: /lib/x86_64-linux-gnu/libc.so.6: version GLIBC_2.32' not found (required by ./dynexsolve)
./dynexsolve: /lib/x86_64-linux-gnu/libc.so.6: version GLIBC_2.33' not found (required by ./dynexsolve)
./dynexsolve: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./dynexsolve)

**Comment by belgeran** [comment]
okay i went a step further... fresh install of ubuntu 22.04... downloaded 22.04 AVX package... didn't work either.... same illegal instruction... please help to resolve.. this basically means the miners only work for hiveOS or windows only..

**Comment by dynexcoin** [comment]
Obsolete by now
