### ISSUE TITLE
dynexsolve crashes with GPUassert: an illegal instruction was encountered kernel.cu 2520

### ISSUE THREAD

**Issue by mharsch** [dynexcoin/Dynex#43]
Hitting this frequently (~once per hour) on otherwise stable rig.

07-02-2023 09:06:24 [GPU 5] GOT CHIPS 189358 TO 190944                                                                                                  
07-02-2023 09:06:28 [INFO] ---------------------------------------------------------                                                                    
07-02-2023 09:06:28 [INFO] STARTING 11892 DYNEX CHIPS ON GPU...                                                                                         
07-02-2023 09:06:30 [MALLOB] ATOMIC STATE UPDATED                                                                                                       
07-02-2023 09:06:30 [BLOCKCHAIN] STARTING DYNEXSOLVE SERVICE                                                                                            
07-02-2023 09:06:36 [GPU 0] 49476916 STEPS (+49476916) | 6.26s | FLOPS = 7908 kFLOPS | HR = 107.409 H | AVG(O)n ^ 0.80797 | CIRCUIT SIMULATION (0.00h)  
07-02-2023 09:06:36 [GPU 1] 33733598 STEPS (+33733598) | 6.26s | FLOPS = 5391 kFLOPS | HR = 66.560 H | AVG(O)n ^ 0.81201 | CIRCUIT SIMULATION (0.00h)   
07-02-2023 09:06:37 [GPU 2] 54846927 STEPS (+54846927) | 6.91s | FLOPS = 7934 kFLOPS | HR = 104.577 H | AVG(O)n ^ 0.81625 | CIRCUIT SIMULATION (0.00h)  
07-02-2023 09:06:43 [GPU 3] 40755054 STEPS (+40755054) | 13.51s | FLOPS = 3017 kFLOPS | HR = 72.236 H | AVG(O)n ^ 0.82505 | CIRCUIT SIMULATION (0.00h)  
07-02-2023 09:06:43 [GPU 4] 61607018 STEPS (+61607018) | 13.51s | FLOPS = 4560 kFLOPS | HR = 106.243 H | AVG(O)n ^ 0.82570 | CIRCUIT SIMULATION (0.00h) 
07-02-2023 09:06:44 [GPU 5] 39787444 STEPS (+39787444) | 13.71s | FLOPS = 2902 kFLOPS | HR = 70.819 H | AVG(O)n ^ 0.82340 | CIRCUIT SIMULATION (0.00h)  
07-02-2023 09:06:44 [GPU *] 280206957 STEPS (+280206957) | 13.71s | FLOPS = 20438 kFLOPS | HR = 527.844 H | AVG(O)n ^ 0.81836                           
07-02-2023 09:06:44 [INFO] POOL HASHRATE 0 (0/0) UPTIME 0                                                                                               
07-02-2023 09:06:56 [GPU 0] 102204558 STEPS (+52727642) | 11.21s | FLOPS = 4703 kFLOPS | HR = 107.409 H | AVG(O)n ^ 0.86695 | CIRCUIT SIMULATION (0.00h)
07-02-2023 09:06:56 [GPU 1] 68718574 STEPS (+34984976) | 11.21s | FLOPS = 3120 kFLOPS | HR = 66.560 H | AVG(O)n ^ 0.86985 | CIRCUIT SIMULATION (0.00h)  
07-02-2023 09:07:00 [GPU 2] 119075337 STEPS (+64228410) | 16.04s | FLOPS = 4004 kFLOPS | HR = 104.577 H | AVG(O)n ^ 0.87926 | CIRCUIT SIMULATION (0.00h)
07-02-2023 09:07:17 [GPU 3] 90103941 STEPS (+49348887) | 32.92s | FLOPS = 1498 kFLOPS | HR = 72.236 H | AVG(O)n ^ 0.88954 | CIRCUIT SIMULATION (0.00h)  
07-02-2023 09:07:17 [GPU 4] 138331403 STEPS (+76724385) | 32.93s | FLOPS = 2330 kFLOPS | HR = 106.243 H | AVG(O)n ^ 0.89145 | CIRCUIT SIMULATION (0.00h)
07-02-2023 09:07:22 [GPU 5] 88494981 STEPS (+48707537) | 37.90s | FLOPS = 1285 kFLOPS | HR = 70.819 H | AVG(O)n ^ 0.88839 | CIRCUIT SIMULATION (0.00h)  
07-02-2023 09:07:22 [GPU *] 606928794 STEPS (+326721837) | 37.90s | FLOPS = 8620 kFLOPS | HR = 527.844 H | AVG(O)n ^ 0.88119                            
07-02-2023 09:07:22 [INFO] POOL HASHRATE 0 (0/0) UPTIME 14                                                                                              
07-02-2023 09:07:22 [STRATUM] CONNECTING TO dnx.us.ekapool.com:19666                                                                                    
07-02-2023 09:07:23 [STRATUM] CONNECTED, LOGGING IN...                                                                                                  
07-02-2023 09:07:23 [STRATUM] AUTHORIZED                                                                                                                
07-02-2023 09:07:23 [STRATUM] JOB ID 950686405359338 DIFF 15000                                                                                         
07-02-2023 09:07:39 [GPU 0] 160691125 STEPS (+58486567) | 16.13s | FLOPS = 3626 kFLOPS | HR = 107.409 H | AVG(O)n ^ 0.90373 | CIRCUIT SIMULATION (0.01h)
07-02-2023 09:07:39 [GPU 1] 106127647 STEPS (+37409073) | 16.13s | FLOPS = 2319 kFLOPS | HR = 66.560 H | AVG(O)n ^ 0.90518 | CIRCUIT SIMULATION (0.01h) 
07-02-2023 09:07:40 [STRATUM] SUBMITTING PoW: 48480936db7d97bb6038a82537b929512ec5ff0e4935c3ef98fa85b7be440100 NONCE 78353211 DIFF 51663                
GPUassert: an illegal instruction was encountered kernel.cu 2520

**Comment by gabrieldan69** [comment]
same problem here !!!

Driver : 525.78.01

GPUassert: unspecified launch failure kernel.cu 2520

**Comment by mharsch** [comment]
This seems to be OC related.  The following settings seem to eliminate the issue.
`nvtool --setclocks 2100 --setmem 810 --setcoreoffset 255`

**Comment by dynexcoin** [comment]
Obsolete by now
