### ISSUE TITLE
[MALLOB] dynex_compute_w340.cnf NEEDS TO BE DOWNLOADED...  [ERROR] download failed: 56

### ISSUE THREAD

**Issue by fenixfyre42** [dynexcoin/Dynex#46]
Seeing the following error on Windows 11, regardless of the miner running as admin or not:

09-02-2023 13:03:58 [INFO] ---------------------------------------------------------
09-02-2023 13:03:58 [INFO] DynexSolve v2.2.3(a) | Meaningful Mining
09-02-2023 13:03:58 [INFO] ---------------------------------------------------------
09-02-2023 13:03:58 [INFO] STRATUM PROTOCOL ENABLED
09-02-2023 13:03:58 [INFO] STRATUM URL SET TO dnx.sg.ekapool.com
09-02-2023 13:03:58 [INFO] STRATUM PORT SET TO 19666
09-02-2023 13:03:58 [INFO] STRATUM PASSWORD SET TO Natsu
09-02-2023 13:03:58 [INFO] MINING ADDRESS SET TO ----------------Hidden--------------------
09-02-2023 13:03:58 [INFO] OPTION mallob-endpoint SET TO https://dnx.sg.ekapool.com
09-02-2023 13:03:58 [INFO] OPTION multi-gpu ACTIVATED
09-02-2023 13:03:58 [INFO] OPTION no-cpu ACTIVATED
09-02-2023 13:03:58 [INFO] MULTI-GPU ENABLED
09-02-2023 13:03:58 [INFO] CUDA RUNTIME: 11.2
09-02-2023 13:03:58 [INFO] CUDA DRIVER:  12.0
09-02-2023 13:03:58 [INFO] FOUND 1 INSTALLED GPU(s)
09-02-2023 13:03:58 [GPU 0] 2d:00 NVIDIA GeForce RTX 3080 10239 MB (8.6) ADJ = 1.300000
09-02-2023 13:04:03 [MALLOB] REGISTER WORKER: SUCCESS
09-02-2023 13:04:03 [MALLOB] JOB RECEIVED
09-02-2023 13:04:03 [MALLOB] CHIPS AVAILABLE     : 162976/3521856
09-02-2023 13:04:03 [MALLOB] JOB FILENAME        : dynex_compute_w340.cnf
09-02-2023 13:04:03 [MALLOB] JOB FEE             : BLOCK REWARD + 0 DNX
09-02-2023 13:04:03 [MALLOB] JOB SOLUTION REWARD : 100000 DNX
09-02-2023 13:04:03 [MALLOB] NETWORK ID ----------------Hidden--------------------

09-02-2023 13:04:03 [MALLOB] dynex_compute_w340.cnf NEEDS TO BE DOWNLOADED...
 [ERROR] download failed: 56

**Comment by maxiaoxiao769** [comment]
Downloading mallob configuration file dynex_compute_w340.cnf
