### ISSUE TITLE
Dynex v.2.2.2(b) Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by Rolf-Fredrickson** [dynexcoin/Dynex#47]
Downloading the binaries for  v.2.2.2 or  v.2.2.2b **Dynex-main-7106974-ubuntu-20.04-linux-x64**-[all] and running the software using the command

./dynexd  
./simplewallet 
./walletd 

as described in the documentation, all fail with:

**Illegal instruction (core dumped)** error.

**Comment by makertronic** [comment]
I got the same error

**Comment by Link-x86** [comment]
Same issue here with the precompiled binaries for ubuntu 22.04. Compiled from source works fine except for errors syncing at block 108000

**Comment by Link-x86** [comment]
22.04 precompiled binaries in the new 2.2.2c still exhibit Illegal instruction error

**Comment by lazy-tinker** [comment]
Build it from source, this way it works. Follow the instructions from the Readme
