### ISSUE TITLE
macos 12 walletd does not work

### ISSUE THREAD

**Issue by sudormdir** [dynexcoin/Dynex#48]
Failed with error: 
```
dyld[83638]: Library not loaded: @rpath/libboost_system-mt-x64.dylib
  Referenced from: ~/Downloads/Dynex-main-7106974/dynexd
  Reason: tried: '/Users/runner/work/Dynex/Dynex/boost/boost/lib/libboost_system-mt-x64.dylib' (no such file), '/Users/runner/work/Dynex/Dynex/boost/boost/lib/libboost_system-mt-x64.dylib' (no such file), '/usr/local/lib/libboost_system-mt-x64.dylib' (no such file), '/usr/lib/libboost_system-mt-x64.dylib' (no such file)
```

I already have boost installed

**Comment by sudormdir** [comment]
Also want to add that the files aren't even executable until I chmod 755 them

**Comment by dynexcoin** [comment]
You need to have libboost installed. Please follow the guides in the developer section of our main website

**Comment by sudormdir** [comment]
I already said I have boost installed. It turns out I needed the x64 version in order for the program to work, which means this app is not m1 compatible

**Comment by sudormdir** [comment]
> You need to have libboost installed. Please follow the guides in the developer section of our main website

Actually even on an x64 mac brew does not install the exact libboost package the script looks for. The script looks for "libboost_system-mt-x64.dylib" but brew installs "libboost_system-mt.dylib"

**Comment by sudormdir** [comment]
Even after manually changing the dependencies so that the packages do not have "-x64" in front of it the terminal says "zsh: killed ./dynexd"
