### ISSUE TITLE
 [MALLOB] REGISTER WORKER: FAILED

### ISSUE THREAD

**Issue by DonnieBurgs** [dynexcoin/Dynex#52]
[MALLOB] REGISTER WORKER: FAILED
What happen?

**Comment by 13y87t** [comment]
Same for me, 2 days with no problem and now I got this error on all my workers..

**Comment by niagars** [comment]
same situation [MALLOB] REGISTER WORKER: FAILED
now after reeboot

**Comment by lardon06** [comment]
The same for me since this morning (DynexSolve_windows_v 224

**Comment by VDV777** [comment]
+ problem
[MALLOB] REGISTER WORKER: FAILED

**Comment by serkrush** [comment]
same problem

**Comment by MarioCoarasa** [comment]
Same issue. Changing pool same problem. I back to nexa for now.

**Comment by CorsaH** [comment]
It's working now. Thank me laters :>

**Comment by BudiBud** [comment]
Same problem: [MALLOB] REGISTER WORKER: FAILED

**Comment by EpicFalling** [comment]
same issue,any solutions?

**Comment by 13y87t** [comment]
Apparently, just need to wait.
It's funny because everything is fucked since 2 days and nothing is do, when I say this project is a scam...

**Comment by Kikounette** [comment]
update to 2.2.5 miner...

https://github.com/dynexcoin/Dynex/releases

**Comment by Kikounette** [comment]
someone knows that following issue ?

"GPU assert: out of memory C:/DYNEX/DynexSolve/DynexSolveVS/DynexSolveVS/kernel.cu 1171"

4 similar RTX 3090's -> If I disable one GPU, then it start to mine without error

**Comment by jeanpoly** [comment]
@Kikounette  and how  did you pass  over the  worker registration error  mentioned above ?

**Comment by ivanpop** [comment]
> @Kikounette and how did you pass over the worker registration error mentioned above ?

After a couple of tries it will register.

**Comment by garvit31** [comment]
its not working for me yet kindly help out

**Comment by 13y87t** [comment]
Srbminer have fucked everything

**Comment by dynexcoin** [comment]
We believe this is outdated by now as commercial miners have overtaken most of the hashrate on Dynex.
