### ISSUE TITLE
DynexSolve Version 2.2.4 (12 GPU load 100% CPU)

### ISSUE THREAD

**Issue by amdsys** [dynexcoin/Dynex#55]
-sync  -no-cpu failure

**Comment by 13y87t** [comment]
Same for me, but It's like this since I began mining this.
That I write -no-cpu or not, miner say "no-cpu option ACTIVATED" 
for -sync command, there is no change with or without it

**Comment by Salvo52** [comment]
i have too low HR with my 3090, only 115h/s, i don't think it's because i have a old i7 ?

**Comment by 13y87t** [comment]
hiveos or windows ? 
what oc ? 
hashrate reported or real ?

**Comment by dynexcoin** [comment]
We believe that is outdated by now
