### ISSUE TITLE
pool hash issue

### ISSUE THREAD

**Issue by EpicFalling** [dynexcoin/Dynex#58]
![resim_2023-03-05_195327877](https://user-images.githubusercontent.com/127021047/222974363-8df160bc-deb6-4e5e-9d75-3b6391e9b9db.png)

it only posts 120 hash to pool,it should be around 1000 hash,how can i fix that?

**Comment by 13y87t** [comment]
With waiting and/or new cpu

**Comment by EpicFalling** [comment]
> With some waiting and/or new cpu

i did not understand,what do you mean

**Comment by 13y87t** [comment]
Sorry, i'm not english
Your rig is up since 8min, you need to wait until hashrate goes up. If it don't goes up, your cpu is too weak

**Comment by EpicFalling** [comment]
i have never seen a problem with cpu at mining

**Comment by 13y87t** [comment]
find out how dynex works
