### ISSUE TITLE
[MALLOB] REGISTER WORKER: FAILED

### ISSUE THREAD

**Issue by VDV777** [dynexcoin/Dynex#61]
Sometime (every 1-5 min) i have this error < [MALLOB] REGISTER WORKER: FAILED> on new ver. 225, same on old version.
what's problem?

**Comment by garvit31** [comment]
no clue dude they are not even helping out i am trying to reach for past 48 hours

**Comment by dynexcoin** [comment]
This issue needs to be addressed with your pool operator / mining software developer
