### ISSUE TITLE
[MALLOB] REGISTER WORKER: FAILED

### ISSUE THREAD

**Issue by Tkz007** [dynexcoin/Dynex#63]
I have i7 7700k and 5GPUs connected (2 rtx 3090 and 3 rtx3080ti). Does anyone know how to solve?

**Comment by MMGG135** [comment]
i have a problem yesterday and this is mi configuration working today. 
![config  hoja de vuelo neuropool dynex] (https://user-images.githubusercontent.com/127419547/224063013-df977e2b-dc08-4350-a244-fed1cb83c5ae.jpg)

**Comment by garvit31** [comment]
its still not working showing the same error 
i think the devs are dumb af they are not even trying solve the shit

**Comment by dynexcoin** [comment]
This issue needs to be addressed with your pool operator / mining software developer
