### ISSUE TITLE
Miner crashes a few seconds after starting... (Windows)

### ISSUE THREAD

**Issue by noebranco** [dynexcoin/Dynex#64]
The miner starts, I get to see some lines and it crashes a few seconds after starting...
I have a multi-gpu rig with 2 1660ti, 1 3060 and a 3060ti.
Batch file is correct.
Any ideas?
Thanks for the help.

**Comment by PositiveK** [comment]
Same issue

**Comment by dynexcoin** [comment]
This issue needs to be addressed with your pool operator / mining software developer
