### ISSUE TITLE
[ERROR] unable to get GPU ammount

### ISSUE THREAD

**Issue by dieselbag** [dynexcoin/Dynex#65]
Tried -multi-gpu and -deviceid 0,1 using hiveos miner
![Screenshot 2023-03-10 111649](https://user-images.githubusercontent.com/25597357/224406646-c2652035-70a1-41de-9d7a-e277855a9011.png)

**Comment by Conspectu** [comment]
I had this issue using dynexsolve custom miner on hive, but I have AMD cards, i solved it using srbminer instead

**Comment by yrx973744218** [comment]
Anyone help me？RX580
![image](https://user-images.githubusercontent.com/62285905/230779330-25154aa1-ef70-4b5e-81fe-0638ad808293.png)

**Comment by dynexcoin** [comment]
This issue needs to be addressed with your pool operator / mining software developer

**Comment by abadilla0608** [comment]
![Screenshot 2023-08-23 200443](https://github.com/dynexcoin/Dynex/assets/143051380/3647be02-8b2d-40f0-a8f1-a3c050c56a3c)
Marca esta opcion
