### ISSUE TITLE
Hashrate is WRONG !!!

### ISSUE THREAD

**Issue by gabrieldan69** [dynexcoin/Dynex#66]
I get in the dynexsolve window in hiveos:

[GPU *] DYNEX CHIPS 3032 | LOCAL MINIMA 19505 | LOWEST ENERGY 41838 | TOTAL HASHRATE 2365 | UPTIME 500

In the main hiveos window  is get 740H/s

At the pool i get 840h/s (  700-860 max)

Why is the hashrate so chaotic ???    I should get ~ 2350h/s   shown also in the pool also in the hiveos main window.

**Comment by 13y87t** [comment]
Use srb miner
