### ISSUE TITLE
[Windows] miner just stops after a while - no errors

### ISSUE THREAD

**Issue by nCr78** [dynexcoin/Dynex#68]
I don't get it. You are into PoUW crypto mining neuromorphic blockchain technologies with a few other buzz words and yet you can't write a windows/linux program in a way that doesn't crash, or if it does to simply restart the process.

No crash logs on the solver / miner, no error messages, no watchdog, nothing.

**Comment by gabrieldan69** [comment]
this also raises me questions....

**Comment by noebranco** [comment]
It only works for me if I use 1 card at a time, otherwise it crashes after 3 or 4 seconds...

**Comment by dynexcoin** [comment]
This issue needs to be addressed with your pool operator / mining software developer
