### ISSUE TITLE
Mallob error: [Timeout was reached] on windows ussing srbminer 2.2.5

### ISSUE THREAD

**Issue by rduran765** [dynexcoin/Dynex#74]
Mallob error: [Timeout was reached] on windows ussing srbminer 2.2.5 conect on ekpool

![imagen](https://user-images.githubusercontent.com/132755608/236622748-14d4a15e-0178-48c5-a6cc-c32af28f6976.png)

**Comment by aguarduso** [comment]
hola, tengo el mismo problema. lo pudiste resolver? gracias

**Comment by dynexcoin** [comment]
This issue needs to be addressed with your pool operator / mining software developer
