### ISSUE TITLE
Dynex executables do not work on macos 

### ISSUE THREAD

**Issue by sudormdir** [dynexcoin/Dynex#77]
My issue was closed as completed but it definitely was not. 
I have boost installed but the packages the executable looks for have "-x64" appended to them. Brew does not install those packages. If I simply erase the "-x64" at the end of the packages so they match what brew installs then the output I get is "zsh: killed          sudo ./dynexd"

**Comment by dynexcoin** [comment]
Which OS exactly are you using? Maybe M1 or M2? In this case you need to build on Rosetta

**Comment by sudormdir** [comment]
I tried on both an M1 running 12.6.3 and an intel i7 running macos 12.6.6

**Comment by sudormdir** [comment]
While the binaries don't work building from source does... kinda. I say kinda because of another issue I will open. However, building on source according to the instructions in the readme does the trick on an intel macbook. It fails on an M1 because of a clang error (The clang compiler does not support -march=native) and I'm not sure how to go in and fix this in the source code

**Comment by sudormdir** [comment]
While the binaries don't work building from source does... kinda. I say kinda because of another issue I will open. However, building on source according to the instructions in the readme does the trick on an intel macbook. It fails on an M1 because of a clang error (The clang compiler does not support -march=native) and I'm not sure how to go in and fix this in the source code
