### ISSUE TITLE
Error subimmting share: Too many shares pending

### ISSUE THREAD

**Issue by tribbianiminer** [dynexcoin/Dynex#78]
Hi guys!

I am a HiveOS user and I have a problem with the miner.
I have tried with several pools, and two different wallets and in all cases I do not get shares, the error appears: "Connection terminated: Error submitting shre: Too many pending shares" attached screenshot.
Apparently, it connects correctly to the pool and the hasrate is good 14.44Kh with two 3080Ti. But there are no valid or rejected shares either.

Can anybody help me?

Thank you so much!
![error summiting shares2](https://github.com/dynexcoin/Dynex/assets/137277931/69fae4f3-39a2-4f24-a336-76a02fffab58)

**Comment by dynexcoin** [comment]
Unfortunately is this out of our control - best to contact either the miner developer or a pool operator.
