### ISSUE TITLE
DYNEXD - Synchronization Problem

### ISSUE THREAD

**Issue by SeeTheInvisible** [dynexcoin/Dynex#8]
Since today morning (that's at least where first noticed it) I see the following log entries which are repeatedly occuring since then:

09:26:23.361501 INFO SYNCHRONIZATION started
09:26:23.409769 INFO Failed to check ring signature for tx <b1cf2ab529a75f1f28944e4295c72d391bb1766a949a3be56c6c1425614da33b>
09:26:23.857745 INFO ----- BLOCK ADDED AS ALTERNATIVE ON HEIGHT 10439
09:26:23.857745 INFO id:	<c8b8bab4b4edacc7c03d497a4038a4e44ec9e8e809be9e78563e65aea39f705d>
09:26:23.857745 INFO PoW:	<60d1043fe2e6e0ed84e4dc3619d36e3f5d728d9440e76b11f935106163000000>
09:26:23.857745 INFO difficulty:	2903460
09:26:23.877891 INFO ----- BLOCK ADDED AS ALTERNATIVE ON HEIGHT 10440
09:26:23.877891 INFO id:	<c5e2b90026bda92bbde52749c2275c96d88f74f9369e4712c9ec1add827a868e>
09:26:23.877891 INFO PoW:	<bdd180a1b504b99bd4f350bcac814beaa150033a8f601a2b8eac103dc1020000>
09:26:23.877891 INFO difficulty:	2914155
09:26:23.900274 INFO ----- BLOCK ADDED AS ALTERNATIVE ON HEIGHT 10441
09:26:23.900274 INFO id:	<e557cdcb5993517f15bc5173e31659a5cd71c52a7d8ac229131d7f7a70e79be5>
09:26:23.900274 INFO PoW:	<cef131a91ded7ae2d21eb5e7984286b874bbf1526759e074dc961a0e2c040000>
09:26:23.900274 INFO difficulty:	2917453
09:26:23.919460 INFO ----- BLOCK ADDED AS ALTERNATIVE ON HEIGHT 10442
09:26:23.919460 INFO id:	<b4d62dfc9d7650f596ecbc3ab9dc5c5f7604d90f8bb07e422cfe63048d0d4b84>
09:26:23.919460 INFO PoW:	<9eae8e7bd78b3583a956d882af3387816dfe49221416133861ae5f1c66030000>
09:26:23.919460 INFO difficulty:	2917717
09:26:23.943307 INFO ----- BLOCK ADDED AS ALTERNATIVE ON HEIGHT 10443
09:26:23.943307 INFO id:	<2995c856d87987a1d9e62bcaba8f615227b131943397cb5332d8775e20f744b7>
09:26:23.943307 INFO PoW:	<c3c527979d5e8203a585da657bbc8189c667fb2bbf85ea91ed372636d9020000>
09:26:23.943307 INFO difficulty:	2915520
09:26:23.961067 INFO ----- BLOCK ADDED AS ALTERNATIVE ON HEIGHT 10444
09:26:23.961067 INFO id:	<32c8d6b3de315f3bcea89a3fd99aa88edb2fcbbc29a0577971b1191be763d846>
09:26:23.961067 INFO PoW:	<77b34783d87206156f09fa037149219263db435ca2d55282e50eb1acc4000000>
09:26:23.961067 INFO difficulty:	2890361
09:26:23.983155 INFO ----- BLOCK ADDED AS ALTERNATIVE ON HEIGHT 10445
09:26:23.983155 INFO id:	<b9f3fd1693402f52b63381dfac89f0734674001bd3551d60ee482d633c225798>
09:26:23.983155 INFO PoW:	<7ab3f3a7164b6705bfa79837600bb00b67446279197850cea6faf3bc2f020000>
09:26:23.983155 INFO difficulty:	2887034
09:26:24.008395 INFO ----- BLOCK ADDED AS ALTERNATIVE ON HEIGHT 10446
09:26:24.008395 INFO id:	<0c803ae5f653b2e0d0ec0efe0a0e31e7974d5f9a3aede6167342837e4a062694>
09:26:24.008395 INFO PoW:	<bd97704f0c43cfbbcf6abd8ae046705e2c02eea31b72d14d4b2799ec55000000>
09:26:24.008395 INFO difficulty:	2895911
09:26:24.030208 INFO ###### REORGANIZE on height: 10439 of 10446 with cum_difficulty 7950946605
09:26:24.030208 INFO  alternative blockchain size: 9 with cum_difficulty 7953836883
09:26:24.049347 INFO Failed to check ring signature for tx <b1cf2ab529a75f1f28944e4295c72d391bb1766a949a3be56c6c1425614da33b>
09:26:24.049508 INFO Block <c8b8bab4b4edacc7c03d497a4038a4e44ec9e8e809be9e78563e65aea39f705d> has at least one transaction with wrong inputs: <b1cf2ab529a75f1f28944e4295c72d391bb1766a949a3be56c6c1425614da33b>
09:26:24.053814 INFO Failed to check ring signature for tx <b1cf2ab529a75f1f28944e4295c72d391bb1766a949a3be56c6c1425614da33b>
09:26:24.053918 INFO Failed to switch to alternative blockchain
09:26:24.224540 INFO Rollback success.
09:26:24.224607 INFO The block was inserted as invalid while connecting new alternative chain,  block_id: <c8b8bab4b4edacc7c03d497a4038a4e44ec9e8e809be9e78563e65aea39f705d>
09:26:33.525763 INFO [162.55.209.214:17333 OUT] Sync data returned unknown top block: 10446 -> 10642 [196 blocks (0 days) behind] 
09:26:33.525763 INFO SYNCHRONIZATION started

I also tried to update the executables but had to switch back to use the old ones as the downloaded files aren't recognized as executable by Mac OS. I downloaded the files from this location: https://github.com/dynexcoin/Dynex/releases/tag/Dynex_macos

Any ideas how to solve the failed synchronization issue?

Cheers & Thank in advance

**Comment by dynexcoin** [comment]
IMPORTANT MESSAGE TO ALL PARTICIPANTS +++ UPDATE TO LATEST VERSION

Unfortunately have we not been able to get in touch with the three nodes which have been constantly trying to submit incorrect blocks into our beautiful Dynex blockchain. I'm sure most of you have noticed that the chain tried to repair and rebuild itself continuously (which shows that the chain itself can correct itself), but at the cost of making mining new blocks quit problematic. We therefore just released the source codes as well as Windows, MacOS and Linux binaries with an update to get the situation resolved. We will NOT allow old nodes to continue to connect and to participate. The cut was introduced at block 10708. Therefore, please:

1) Download (or build) the latest version from our GitHub
2) Delete the .DYNEX data directory (which might still have dust inside). The new daemon will NOT start if you have not deleted the directory. If you don't know where the .DYNEX directory is located, run "dynexd --help" - this will show you the location of the data-dir
3) Now run "dynexd" - the daemon will synchronise with the clean blockchain. this will take a few minutes.

Please note that all wallet balances, historical transactions etc. are not effected (except the incorrect transactions which someone tried to inject). Also note that we chose block 10708 as an interception point from where we fork the access.

Again, we are deeply sorry for any inconvenience caused, we didn't sleep much the last 12 hours but are very relieved that we could resolve the situation.

**Comment by dynexcoin** [comment]
closing as fixed.

**Comment by SeeTheInvisible** [comment]
Thanks, issue has been resolved, it is working again as expected - keep up the great work :)
