### ISSUE TITLE
414 mallob error persistant on zergpool

### ISSUE THREAD

**Issue by realsetvin** [dynexcoin/Dynex#82]
Users have reported for several months (since Dynex was added to ZergPool) that there have been mallob issues (414) using SRBMiner and also OneZeroMiner on AMDs and NVIDIA. 

The issue appears to happen most often when using multiple GPUs. When users have more than one GPU mining dynex on ZergPool they most often get 414 errors.

Users have tried many things to resolve this, including ensuring their "paid to" address is a dynex address (not auto converting) as well as adjusting difficulty by various magnitudes.

**Comment by dynexcoin** [comment]
Zergpool needs to update to the latest versions which have been released today to fix that issue.
