### ISSUE TITLE
Can't restore wallet with private key

### ISSUE THREAD

**Issue by sudormdir** [dynexcoin/Dynex#83]
I copied the private key and pasted it into simplewallet after selecting "Restore backup/paperwallet" but it told me it was the wrong private key. Curiously enough, importing by tracking key as well as by private spend/view keys does work. This was tested on an Intel Mac

**Comment by sudormdir** [comment]
Curiously enough, importing by tracking key does work. Also this is on an intel mac

**Comment by dynexcoin** [comment]
Specify --wallet-file and -restore to restore from passphrase or consult -h for options to restore from keys
