### ISSUE TITLE
Virus detected !!!  Win32/Wacatac.B!ml and Program:Win32/Wacapew.C!ml 

### ISSUE THREAD

**Issue by gabrieldan69** [dynexcoin/Dynex#89]
Win32/Wacatac.B!ml and Program:Win32/Wacapew.C!ml

**Comment by staking-explorer** [comment]
> Win32/Wacatac.B!ml and Program:Win32/Wacapew.C!ml

What did you want from scammers with a huge premine? Not only do they have viruses in their wallet, but they also have backdoors in the miner. It is not surprising that major miner developers announced a boycott of this scam called Dynex. After the scandal with the ban of SRBminer, backdoors in their miner and viruses in wallets, the coin is gradually sinking to the bottom...

**Comment by dynexcoin** [comment]
This is a false positive (which happens with most of crypto wallets in general). The wallet has been independently audited by multiple security firms, the code is open source, of course does it not contain any malicious code or virus. Exclude the file in your windows defender.
