### ISSUE TITLE
SYNCHRONIZATION Problem

### ISSUE THREAD

**Issue by SeeTheInvisible** [dynexcoin/Dynex#9]
Just checked my DYNEDXD seemingly it hangs since 3 days doing this:

08:35:12.839164 INFO SYNCHRONIZATION started
08:35:13.730757 WARNING [137.220.61.126:17333 OUT] Exception in connectionHandler: std::bad_alloc
08:35:23.361970 INFO [118.69.64.210:17333 OUT] Sync data returned unknown top block: 12045 -> 14807 [2762 blocks (3 days) behind] 
08:35:23.361970 INFO SYNCHRONIZATION started
08:35:24.460048 WARNING [118.69.64.210:17333 OUT] Exception in connectionHandler: std::bad_alloc
08:35:53.503497 INFO [88.81.81.67:17333 OUT] Sync data returned unknown top block: 12045 -> 14808 [2763 blocks (3 days) behind] 
08:35:53.503497 INFO SYNCHRONIZATION started
08:35:53.885629 WARNING [88.81.81.67:17333 OUT] Exception in connectionHandler: std::bad_alloc
08:36:04.045116 INFO [118.69.64.210:17333 OUT] Sync data returned unknown top block: 12045 -> 14808 [2763 blocks (3 days) behind] 
08:36:04.045116 INFO SYNCHRONIZATION started
08:36:05.480747 WARNING [118.69.64.210:17333 OUT] Exception in connectionHandler: std::bad_alloc
08:36:14.477369 INFO [137.220.61.126:17333 OUT] Sync data returned unknown top block: 12045 -> 14808 [2763 blocks (3 days) behind] 
08:36:14.477369 INFO SYNCHRONIZATION started
08:36:15.738857 WARNING [137.220.61.126:17333 OUT] Exception in connectionHandler: std::bad_alloc
08:36:29.593139 INFO [95.179.252.220:17333 OUT] Sync data returned unknown top block: 12045 -> 14808 [2763 blocks (3 days) behind] 
08:36:29.593139 INFO SYNCHRONIZATION started
08:36:30.036017 WARNING [95.179.252.220:17333 OUT] Exception in connectionHandler: std::bad_alloc

**Comment by dynexcoin** [comment]
Seems your node needs to resync with the network. easiest way is to delete the ./DYNEX data directory and restart dynexd. Let us know if that fixes the problem.

**Comment by SeeTheInvisible** [comment]
Ok, it works again, deleting the ./DYNEX directory was the solution - thanks for your help!

**Comment by dynexcoin** [comment]
You are welcome!
